# Generated by Django 5.2.1 on 2025-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0003_post_reading_time_ticket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(verbose_name='زمان مطالعه'),
        ),
    ]
