# Generated by Django 5.2.1 on 2025-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0004_alter_post_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='اسلاگ'),
        ),
    ]
