# Generated by Django 5.2.1 on 2025-05-20 16:01

import django_resized.forms
import test01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=test01.models.user_directory_path, verbose_name='عکس'),
        ),
    ]
